kind: Deployment
apiVersion: apps/v1

metadata:
  name: goserver
  labels:
    app: goserver

spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
    spec:
      containers:
        - name: goserver
          image: bcdscrypto/go-test:v4
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: goserver-env
            - secretRef:
                name: goserver-secret
          volumeMounts:
            - mountPath: "/go/myfamily"
              name: config
      volumes:
        - name: config
          configMap:
            name: configmap-family
            items:
              - key: members
                path: "myfamily.txt"